version: 0.2

env:
  variables:
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Building backend image...
      - docker build -t 381492221394.dkr.ecr.us-east-1.amazonaws.com/three-tier-backend:$IMAGE_TAG ./backend
      - docker push 381492221394.dkr.ecr.us-east-1.amazonaws.com/three-tier-backend:$IMAGE_TAG

      - echo Building frontend image...
      - docker build -t 381492221394.dkr.ecr.us-east-1.amazonaws.com/three-tier-frontend:$IMAGE_TAG ./frontend
      - docker push 381492221394.dkr.ecr.us-east-1.amazonaws.com/three-tier-frontend:$IMAGE_TAG
  post_build:
    commands:
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region us-east-1 --name three-tier-cluster

      - echo Replacing image tags in deployment files...
      - sed -i "s|381492221394.dkr.ecr.us-east-1.amazonaws.com/three-tier-backend:.*|381492221394.dkr.ecr.us-east-1.amazonaws.com/three-tier-backend:$IMAGE_TAG|" k8s/backend-deployment.yaml
      - sed -i "s|381492221394.dkr.ecr.us-east-1.amazonaws.com/three-tier-frontend:.*|381492221394.dkr.ecr.us-east-1.amazonaws.com/three-tier-frontend:$IMAGE_TAG|" k8s/frontend-deployment.yaml

      - echo Applying Kubernetes manifests...
      - kubectl apply -f k8s/
artifacts:
  files:
    - k8s/*.yaml
