version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker push $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - aws eks update-kubeconfig --region us-east-1 --name three-tier-cluster
      - sed -i "s|381492221394.dkr.ecr.us-east-1.amazonaws.com/three-tier-backend|$REPOSITORY_URI:$IMAGE_TAG|" k8s/backend-deployment.yaml
      - sed -i "s|381492221394.dkr.ecr.us-east-1.amazonaws.com/three-tier-frontend|$REPOSITORY_URI:$IMAGE_TAG|" k8s/frontend-deployment.yaml
      - kubectl apply -f k8s/
artifacts:
  files:
    - k8s/*.yaml
