apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: three-tier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 381492221394.dkr.ecr.us-east-1.amazonaws.com/three-tier-backend
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: rds-secret
